Authentication and QOL changes
os-js/osjs-xpra-application pull request #8
Opened 2021-12-27 21:05 UTC by ShadowEO

- Added authentication as per my request #6
- Moved Settings dialog into it's own menu option to help facilitate saving settings.
- Added rudimentary auto-login feature.

Currently the password is saved in plain-text in the client storage (whether this be on the server, or in the browser). This at least satisfies the use-case of authenticated Xpra use, if someone can provide a more secure way to store/retrieve the password, I'd be open to it.

(Recreated on request)

2021-12-27 21:07 UTC, ShadowEO commented
Hopefully this PR works better for you. Great project btw, combining it with Xpra makes it exceptionally powerful. You may be seeing more contributions from me in the future as I attempt to make OS.js suit my needs!

2021-12-27 21:08 UTC, andersevenrud commented
Thanks!

And it seems like the workflow triggered this time :tada:

2021-12-27 21:08 UTC, ShadowEO commented
I see some linting issues, I'll work to fix those when I get back to my workstation

2021-12-27 21:08 UTC, andersevenrud commented
Yup. I'll finish up the review once you get those fixed :smile:

2021-12-27 23:27 UTC, ShadowEO commented
Alright, I fixed everything eslint complained about though there was one line that threw a warning (which was part of the original code, I didn't touch the websocket parts).

2022-01-05 18:18 UTC, andersevenrud requested changes

2022-01-05 18:18 UTC, andersevenrud commented on index.js
> +  let defaultOptions = {
Revert this back to a `const`.

2022-01-05 18:18 UTC, andersevenrud commented on index.js
> +              defaultOptions = options;
Then change this to `Object.assign(defaultOptions, options)`

2022-01-05 22:56 UTC, ShadowEO reviewed
I've made the changes in my fork as requested. Please review at your leisure :D

2022-01-06 15:41 UTC, andersevenrud approved these changes
LGTM. I still need to take it for a quick test drive before merging :)

2022-03-07 03:20 UTC, merged